// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingPlatform.Data.Context;

#nullable disable

namespace TradingPlatform.Data.Migrations
{
    [DbContext(typeof(TradingPlatformDbContext))]
    [Migration("20260421165000_PopulateAdminEntity")]
    partial class PopulateAdminEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model configuration stays the same as AddAdminEntity migration
            // This is a data-only migration, no schema changes
#pragma warning restore 612, 618
        }
    }
}
