// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingPlatform.Data.Context;

#nullable disable

namespace TradingPlatform.Data.Migrations
{
    [DbContext(typeof(TradingPlatformDbContext))]
    partial class TradingPlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingPlatform.Data.Entities.MarketAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChangePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("MarketAssets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ChangePercent = 1.42m,
                            Currency = "USD",
                            Name = "Apple",
                            Price = 214.32m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ChangePercent = 0.87m,
                            Currency = "USD",
                            Name = "Microsoft",
                            Price = 428.11m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ChangePercent = 3.18m,
                            Currency = "USD",
                            Name = "NVIDIA",
                            Price = 902.55m,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ChangePercent = -1.24m,
                            Currency = "USD",
                            Name = "Tesla",
                            Price = 181.09m,
                            Symbol = "TSLA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
